server:
  port: 8001


spring:
  profiles:
    active: test

# 微服务提供者配置
dubbo:
  application:
    name: Provider1
  registry:
    address: zookeeper://139.224.254.0:2181
  scan:
    base-packages:
      org.lwj.Provider1.**  